Fix calling $.get() and $.post() without callback
Without this fix, omitting the "callback" parameter causes an error because in the function "shoestring.ajax" the variable "settings.success" is undefined.

$.get('/')
Uncaught TypeError: undefined is not a function

$.post('/', {})
Uncaught TypeError: undefined is not a function